import Head from 'next/head'
import { ApolloProvider } from '@apollo/client'
import GqlClient from '../graphql/apollo-client'
import '../styles/globals.css'
import { GlobalStyles } from './GlobalStyles'
import Header from '../components/Header/Header'
import type { AppProps } from 'next/app'



export default function App({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>Dungeons Organizer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ApolloProvider client={GqlClient}>
        <GlobalStyles />
        <Component {...pageProps} />
      </ApolloProvider>
    </>
  )
}
