import Head from 'next/head'
import { usePageLoading } from '../hooks/usePageLoading'
import { ApolloProvider } from '@apollo/client'
import GqlClient from '../graphql/apollo-client'
import Header from '../components/Header/Header'
import Loader from '../components/Loader/Loader'
import { GlobalStyles } from './GlobalStyles'
import RoutesAnimation from './RoutesAnimation'
import type { AppProps } from 'next/app'

export default function App({ Component, pageProps }: AppProps) {

  const { isPageLoading } = usePageLoading()

  return (
    <>
      <Head>
        <title>Dungeons Organizer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ApolloProvider client={GqlClient}>
        <GlobalStyles />
        {isPageLoading ?
          <Loader />
          :
          <RoutesAnimation>
            <Component {...pageProps} />
          </RoutesAnimation>
        }

      </ApolloProvider>
    </>
  )
}
